/// <reference types="@raycast/api">

/* 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧

This file is auto-generated by Raycast. DO NOT MODIFY MANUALLY.
Instead, modify the "preferences" in the package.json and run `ray build` to update this file.

🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 🚧 */

declare namespace Preferences {
  /** Preferences for search-prompts */
  export interface SearchPrompts {
    /** Default category filter */
    defaultCategory?: string;
    /** Show favorites first */
    showFavoritesFirst?: boolean;
  }

  /** Preferences for manage-prompts */
  export interface ManagePrompts {
    /** Default category for new prompts */
    defaultCategory?: string;
  }
}
